export const removeList = [
  "The Stylish One",
  "Important Patient",
  "Bloodhounds",
  "Hint",
  "Failed Setup",
  "Hustle",
  "Tourists",
  "Cocktail Tasting",
  "Overseas Trust - Part 1",
  "Overseas Trust - Part 2",
  "The Punisher Harvest",
  "The Tarkov Mystery",
  "To Great Heights - Part 1",
  "To Great Heights - Part 2",
  "To Great Heights - Part 3",
  "A Key to Salvation",
  "Import ontrol",
  "Whats Your Evidence",
  "Caught Red-Handed",
  "Gunsmith - Special Order",
  "Gun Connoisseur",
  "Customer Communication",
  "Supply and Demand",
  "Into the Inferno",
  "In and Out",
  "Ours by Right",
  "Provide Cover",
  "Cream of the Crop",
  "Before the Rain",
  "Night of The Cult",
  "The Graven Image",
  "Dont Believe Your Eyes",
  "Dirty Blood",
  "Burn It Down",
  "The Root Cause",
  "Matter of Technique",
  "Find the Source",
  "Gloves Off",
  "Sample IV - A New Hope",
  "Darkest Hour Is Just Before Dawn",
  "Radical Treatment",
  "Forgotten Oaths",
  "Global Threat",
  "Watch the Watcher",
  "Not a Step Back",
  "Pressured by Circumstances",
  "Conservation Area",
  "Contagious Beast",
];

export const traderUnlockExample = {
  availableInGameEditions: [],
  id: "5d78c49786f7745041358b58", // Needs custom id
  index: 0,
  target: "5c0647fdd443bc2504c2d371", // Set the trader ID here
  type: "TraderUnlock",
  unknown: false,
};
