// Determines which quests unlock fences first quest
export const fenceStartRequiredQuests = [
  "Shortage",
  // "The Punisher - Part 6",
  // "Painkiller",
  // "Chemical - Part 4",
  // "Eagle Eye",
  // "Farming - Part 4",
  // "The Key to Success",
  // "Nostalgia",
];

// TODO: run test to see if the trader unlocks are correct
// This is a list of quests that unlock traders, if empty, the trader is unlocked by default.
// FENCE: "Acquaintance", // fence is always unlocked, but the his first quest is set via above fenceStartRequiredQuests
// LIGHTHOUSEKEEPER: "", // This trader is unlocked by finishing Network Provider - Part 2
// BTR: "", // This trader is unlocked by finishing "Shipping Delay - Part 1"

// These are deprecated quests, or problematic
export const removeList = [
  "Illegal Logging",
  "Chilly",
  "Enough Drinks for That One",
  "Hide in Plain Sight",
  "This Is My Party",
  "A Healthy Alternative",
  "Kind of Sabotage",
  "The Stylish One",
  "Important Patient",
  "Bloodhounds",
  "Hint",
  "Failed Setup",
  "Hustle",
  "Tourists",
  "Cocktail Tasting",
  "Overseas Trust - Part 1",
  "Overseas Trust - Part 2",
  "The Punisher Harvest",
  "The Tarkov Mystery",
  "To Great Heights - Part 1",
  "To Great Heights - Part 2",
  "To Great Heights - Part 3",
  "A Key to Salvation",
  "Import ontrol",
  "Whats Your Evidence",
  "Caught Red-Handed",
  "Gunsmith - Special Order",
  "Gun Connoisseur",
  "Customer Communication",
  "Supply and Demand",
  "Into the Inferno",
  "In and Out",
  "Ours by Right",
  "Provide Cover",
  "Cream of the Crop",
  "Before the Rain",
  "Night of The Cult",
  "The Graven Image",
  "Dont Believe Your Eyes",
  "Dirty Blood",
  "Burn It Down",
  "The Root Cause",
  "Matter of Technique",
  "Find the Source",
  "Gloves Off",
  "Sample IV - A New Hope",
  "Darkest Hour Is Just Before Dawn",
  "Radical Treatment",
  "Forgotten Oaths",
  "Global Threat",
  "Watch the Watcher",
  "Not a Step Back",
  "Pressured by Circumstances",
  "Conservation Area",
  "Contagious Beast",
];
